CREATE TABLE IF NOT EXISTS product_categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  parent_id INT NULL,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NULL,
  image_url VARCHAR(1000) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_parent_id (parent_id),
  INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  source_platform VARCHAR(50) NOT NULL DEFAULT 'tiktok_shop',
  source_product_id VARCHAR(80) NOT NULL,
  source_seller_id VARCHAR(80) NULL,
  source_product_url TEXT NULL,
  source_file VARCHAR(255) NULL,
  category_id INT NULL,
  name VARCHAR(500) NOT NULL,
  slug VARCHAR(600) NOT NULL,
  short_description TEXT NULL,
  description LONGTEXT NULL,
  ingredients LONGTEXT NULL,
  feeding_guide LONGTEXT NULL,
  brand VARCHAR(255) NULL,
  pet_type VARCHAR(50) NULL,
  product_type VARCHAR(100) NULL,
  main_image_url TEXT NULL,
  image_urls_json LONGTEXT NULL,
  image_count INT NOT NULL DEFAULT 0,
  min_price DECIMAL(15,2) NOT NULL DEFAULT 0,
  max_price DECIMAL(15,2) NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'VND',
  total_stock INT NOT NULL DEFAULT 0,
  reserved_stock INT NOT NULL DEFAULT 0,
  sold_count INT NOT NULL DEFAULT 0,
  rating_average DECIMAL(3,2) NOT NULL DEFAULT 4.80,
  review_count INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  is_imported TINYINT(1) NOT NULL DEFAULT 1,
  imported_at DATETIME NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_source_product (source_platform, source_product_id),
  UNIQUE KEY uq_product_slug (slug),
  INDEX idx_category_id (category_id),
  INDEX idx_active (is_active),
  INDEX idx_price (min_price, max_price),
  INDEX idx_pet_type (pet_type),
  INDEX idx_product_type (product_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_variants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  source_platform VARCHAR(50) NOT NULL DEFAULT 'tiktok_shop',
  source_product_id VARCHAR(80) NOT NULL,
  source_sku_id VARCHAR(80) NOT NULL,
  sku VARCHAR(120) NULL,
  variant_name VARCHAR(500) NULL,
  option_1_name VARCHAR(100) NULL,
  option_1_value VARCHAR(255) NULL,
  option_2_name VARCHAR(100) NULL,
  option_2_value VARCHAR(255) NULL,
  option_3_name VARCHAR(100) NULL,
  option_3_value VARCHAR(255) NULL,
  attributes_json LONGTEXT NULL,
  price DECIMAL(15,2) NOT NULL DEFAULT 0,
  original_price DECIMAL(15,2) NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'VND',
  stock_quantity INT NOT NULL DEFAULT 0,
  reserved_stock INT NOT NULL DEFAULT 0,
  warehouse_id VARCHAR(80) NULL,
  image_url TEXT NULL,
  variant_image_status VARCHAR(100) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  imported_at DATETIME NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_source_sku (source_platform, source_sku_id),
  INDEX idx_product_id (product_id),
  INDEX idx_sku (sku),
  INDEX idx_stock (stock_quantity),
  INDEX idx_price (price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  variant_id INT NULL,
  image_url VARCHAR(1000) NOT NULL,
  local_image_path TEXT NULL,
  image_type VARCHAR(50) NOT NULL DEFAULT 'product',
  is_main TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  source_platform VARCHAR(50) NOT NULL DEFAULT 'tiktok_shop',
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_product_image (product_id, image_url(255)),
  INDEX idx_product_id (product_id),
  INDEX idx_variant_id (variant_id),
  INDEX idx_is_main (is_main)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_import_batches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  source_platform VARCHAR(50) NOT NULL DEFAULT 'tiktok_shop',
  source_file VARCHAR(255) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'running',
  total_products INT NOT NULL DEFAULT 0,
  total_variants INT NOT NULL DEFAULT 0,
  products_created INT NOT NULL DEFAULT 0,
  products_updated INT NOT NULL DEFAULT 0,
  variants_created INT NOT NULL DEFAULT 0,
  variants_updated INT NOT NULL DEFAULT 0,
  images_created INT NOT NULL DEFAULT 0,
  error_count INT NOT NULL DEFAULT 0,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  summary_json LONGTEXT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  INDEX idx_source_platform (source_platform)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_import_rows (
  id INT AUTO_INCREMENT PRIMARY KEY,
  batch_id INT NOT NULL,
  source_product_id VARCHAR(80) NULL,
  source_sku_id VARCHAR(80) NULL,
  row_type VARCHAR(50) NOT NULL DEFAULT 'product',
  action VARCHAR(50) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'success',
  message TEXT NULL,
  raw_json LONGTEXT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_batch_id (batch_id),
  INDEX idx_status (status),
  INDEX idx_source_product_id (source_product_id),
  INDEX idx_source_sku_id (source_sku_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  variant_id INT NULL,
  transaction_type VARCHAR(50) NOT NULL,
  quantity_change INT NOT NULL,
  quantity_before INT NULL,
  quantity_after INT NULL,
  reference_type VARCHAR(50) NULL,
  reference_id VARCHAR(80) NULL,
  note TEXT NULL,
  created_by VARCHAR(100) NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_product_id (product_id),
  INDEX idx_variant_id (variant_id),
  INDEX idx_transaction_type (transaction_type),
  INDEX idx_reference (reference_type, reference_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
